version: '3.1'

services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 55680:55680
  ads:
    image: wso2inc/ads-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
  cart:
    image: wso2inc/cart-service:v0.1.0 #add redis
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
  checkout:
    image: wso2inc/checkout-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: catalogHost="catalog" \n cartHost="cart" \n currencyHost="currency" \n shippingHost="shipping" \n paymentHost="payment" \n emailHost="email" \n \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - catalog
      - cart
      - currency
      - shipping
      - payment
      - email
      - jaeger
    depends_on:
      - catalog
      - cart
      - currency
      - shipping
      - payment
      - email
      - jaeger
  currency:
    image: wso2inc/currency-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
  email:
    image: wso2inc/email-service:v0.1.0
    secrets:
      - source: email_config  
        target: /home/ballerina/Config.toml
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
  frontend:
    image: wso2inc/frontend-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: catalogHost="catalog" \n cartHost="cart" \n recommendHost="recommendation" \n currencyHost="currency" \n shippingHost="shipping" \n checkoutHost="checkout" \n adHost="ads" \n \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    ports:
      - 9098:9098
    links:
      - catalog
      - cart
      - recommendation
      - currency
      - shipping
      - checkout
      - ads
      - jaeger
    depends_on:
      - catalog
      - cart
      - recommendation
      - currency
      - shipping
      - checkout
      - ads
      - jaeger
  payment:
    image: wso2inc/payment-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
  catalog:
    image: wso2inc/catalog-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
  recommendation:
    image: wso2inc/recommendation-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: catalogHost="catalog" \n \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - catalog
      - jaeger
    depends_on:
      - catalog
      - jaeger
  shipping:
    image: wso2inc/shipping-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    links:
      - jaeger
    depends_on:
      - jaeger
secrets:
    email_config:
      file: ./email/Config.toml
